from ij import IJ, WindowManager
analyte = WindowManager.getCurrentImage()
nucChan = IJ.getProperty("nucChan")
analyte.setC(nucChan)
title = analyte.getTitle()
cmNumber = IJ.getProperty("cmNumber")
rt = WindowManager.getWindow("Nucleus Results").getTextPanel().getOrCreateResultsTable()
a = rt.getCounter()
roi = analyte.getRoi()
roiStats = roi.getStatistics()
rt.setValue("Area", a,  roiStats.area)
rt.setValue("Mean", a,  roiStats.mean)
rt.setValue("Integrated Intensity", a, roiStats.area * roiStats.mean)
rt.setValue("Major Axis", a, roiStats.major)
rt.setValue("Minor Axis", a,  roiStats.minor)
rt.setValue("CmNumber", a, cmNumber)
rt.show("Nucleus Results")